version: "3.9"

services:

  # backend
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      MONGODB_HOST: put-your-own
      MONGODB_DATABASE: put-your-own
      MONGODB_USER: put-your-own
      MONGODB_PASSWORD: put-your-own
      GMAIL_USERNAME: put-your-own
      GMAIL_PASSWORD: put-your-own
      PORT: 8000
      JWT_SECRET: qwertyuiopasdfghjklzxcvbnm123456
    networks:
      - to-do-net
  
  # frontend
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - to-do-net
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/nginx/cors.conf:/etc/nginx/cors.conf:ro
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

# networks
networks:
  to-do-net:
    name: to-do-net
    driver: bridge