apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-to-do-backend
  labels:
    app: mern-to-do-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-to-do-backend
  template:
    metadata:
      labels:
        app: mern-to-do-backend
    spec:
      containers:
      - name: backend
        image: meiezbr/mern-to-do-app-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: mongo-host

        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: mongo-database

        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username

        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password

        - name: GMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: gmail-username

        - name: GMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: gmail-password

        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: jwt-secret

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: mern-to-do-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
