apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-to-do-frontend
  labels:
    app: mern-to-do-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-to-do-frontend
  template:
    metadata:
      labels:
        app: mern-to-do-frontend
    spec:
      containers:
      - name: frontend
        image: meiezbr/mern-to-do-app-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: mern-to-do-frontend
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
