apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-host: Y2x1c3RlcjAucHpoa2dsdi5tb25nb2RiLm5ldA==
    mongo-root-username: bWVpZXpicg==
    mongo-root-password: aW5zaWduZTE1OTM1Nw==
    gmail-username: bWF5ZXpicjlAZ21haWwuY29t
    gmail-password: cnFzcyB0Y3dsIHpwa2sgcGppdQ==
    